config/routes.rb
Rails.application.routes.draw do
#CRUD
#Create
#Read
#Update
#Delete

#lire toutes les tasks
get 'tasks', to: 'tasks#index'

post 'tasks', to: 'tasks#create'
get 'tasks/new', to: 'tasks#new'

get 'tasks/:id/edit', to: 'tasks#edit'

get 'tasks/:id', to: 'tasks#show', as: :task

patch 'tasks/:id', to: 'tasks#update'

delete 'tasks/:id', to: 'tasks#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path

  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path

  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>

<% end %>

app/views/tasks/index.html.erb
<h1> List of tasks</h1>
<p>
  <% @tasks.each do |task| %>
  <h2>
    <%= task.title %>
  </h2>
  <p>
    <input type="checkbox">
    </p>
  <%= link_to task.title, task_path(task) %>

  <% end %>
</p>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<div class="container">
  <div class="col-xs-12">
    <%= form_for @task do |f| %>
    <div class="form-inline">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-inline">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>

    <div class="form-inline">
      <%= f.label :completed %>
      <%= f.check_box :completed, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<h1> Tasks </h1>
<p> <%= @task.title %> </p>
<p> <%= @task.details %> </p>
<p> <%= @task.completed %> </p>

<%= link_to "Delete", @task_path,
      method: :delete,
      data: { confirm: "Are you sure?" } %>